// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApfh-i6SNhih23SE1bCwDqB_OecyKQB1o',
    appId: '1:736064564699:web:3797e2b5c9b52be1694bfe',
    messagingSenderId: '736064564699',
    projectId: 'oasis-f5760',
    authDomain: 'oasis-f5760.firebaseapp.com',
    storageBucket: 'oasis-f5760.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMcjqFQ39Va3WqoiLiLyXQb1N7G0Xf3Ok',
    appId: '1:736064564699:android:235f2777a3a9e0da694bfe',
    messagingSenderId: '736064564699',
    projectId: 'oasis-f5760',
    storageBucket: 'oasis-f5760.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0tMQTLY98xhkxs3i6-i2osrwqGB669fs',
    appId: '1:736064564699:ios:975c2886cc9fa36e694bfe',
    messagingSenderId: '736064564699',
    projectId: 'oasis-f5760',
    storageBucket: 'oasis-f5760.appspot.com',
    iosBundleId: 'com.example.oasisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0tMQTLY98xhkxs3i6-i2osrwqGB669fs',
    appId: '1:736064564699:ios:975c2886cc9fa36e694bfe',
    messagingSenderId: '736064564699',
    projectId: 'oasis-f5760',
    storageBucket: 'oasis-f5760.appspot.com',
    iosBundleId: 'com.example.oasisApp',
  );
}
